 var data = [{
   "hanja": "ㅊㅈㅇㄱ",
   "jei_set": "가01",
   "mean": "初志一貫",
   "idiom": "초지일관"
 }, {
   "hanja": "ㅁㅇㄷㅍ",
   "jei_set": "가02",
   "mean": "馬耳東風",
   "idiom": "마이동풍"
 }, {
   "hanja": "ㄷㅁㅅㄷ",
   "jei_set": "가03",
   "mean": "東問西答",
   "idiom": "동문서답"
 }, {
   "hanja": "ㄱㅁㅅㅅ",
   "jei_set": "가04",
   "mean": "見物生心",
   "idiom": "견물생심"
 }, {
   "hanja": "ㅇㅅㅇㅈ",
   "jei_set": "가05",
   "mean": "一石二鳥",
   "idiom": "일석이조"
 }, {
   "hanja": "ㄱㅇㅇㅅ",
   "jei_set": "가06",
   "mean": "甘言利說",
   "idiom": "감언이설"
 }, {
   "hanja": "ㄷㄱㅁㅅ",
   "jei_set": "가07",
   "mean": "大器晩成",
   "idiom": "대기만성"
 }, {
   "hanja": "ㅈㅅㅅㅇ",
   "jei_set": "가08",
   "mean": "作心三日",
   "idiom": "작심삼일"
 }, {
   "hanja": "ㅂㅈㅈㅈ",
   "jei_set": "가09",
   "mean": "父傳子傳",
   "idiom": "부전자전"
 }, {
   "hanja": "ㅈㅇㅈㄷ",
   "jei_set": "가10",
   "mean": "自業自得",
   "idiom": "자업자득"
 }, {
   // 나등급
   "hanja": "ㅇㄱㅇㅇ",
   "jei_set": "나01",
   "mean": "一口二言",
   "idiom": "일구이언"
 }, {
   "hanja": "ㅈㅁㄱㅇ",
   "jei_set": "나02",
   "mean": "竹馬故友",
   "idiom": "죽마고우"
 }, {
   "hanja": "ㅁㅇㅈㅁ",
   "jei_set": "나03",
   "mean": "無用之物",
   "idiom": "무용지물"
 }, {
   "hanja": "ㅇㅈㅇㄷ",
   "jei_set": "나04",
   "mean": "一長一短",
   "idiom": "일장일단"
 }, {
   "hanja": "ㅇㅂㅁㅎ",
   "jei_set": "나05",
   "mean": "有備無患",
   "idiom": "유비무환"
 }, {
   "hanja": "ㄷㄷㅇㅅ",
   "jei_set": "나06",
   "mean": "多多益善",
   "idiom": "다다익선"
 }, {
   "hanja": "ㄷㅈㄷㄴ",
   "jei_set": "나07",
   "mean": "多才多能",
   "idiom": "다재다능"
 }, {
   "hanja": "ㅎㅂㅂㅁ",
   "jei_set": "나08",
   "mean": "行方不明",
   "idiom": "행방불명"
 }, {
   "hanja": "ㅂㄱㅅㅅ",
   "jei_set": "나09",
   "mean": "兵家常事",
   "idiom": "병가상사"
 }, {
   "hanja": "ㅇㅇㅈㅇ",
   "jei_set": "나10",
   "mean": "右往左往",
   "idiom": "우왕좌왕"
 }, {
   "hanja": "ㅇㅂㅇㄹ",
   "jei_set": "나11",
   "mean": "烏飛梨落",
   "idiom": "오비이락"
 }, {
   "hanja": "ㄱㄱㅊㅅ",
   "jei_set": "나12",
   "mean": "改過遷善",
   "idiom": "개과천선"
 }, {
   "hanja": "ㅇㄷㅅㅁ",
   "jei_set": "나13",
   "mean": "龍頭蛇尾",
   "idiom": "용두사미"
 }, {
   "hanja": "ㅁㅇㄷㅅ",
   "jei_set": "나14",
   "mean": "無爲徒食",
   "idiom": "무위도식"
 }, {
   "hanja": "ㅊㅇㅍㅇ",
   "jei_set": "나15",
   "mean": "此日彼日",
   "idiom": "차일피일"
 }, {
   "hanja": "ㅊㅍㅇㄹ",
   "jei_set": "나16",
   "mean": "千篇一律",
   "idiom": "천편일률"
 }, {
   "hanja": "ㅎㅅㄱㄷ",
   "jei_set": "나17",
   "mean": "鶴首苦待",
   "idiom": "학수고대"
 }, {
   "hanja": "ㄷㅁㅂㅊ",
   "jei_set": "나18",
   "mean": "杜門不出",
   "idiom": "두문불출"
 }, {
   "hanja": "ㅈㅂㅇㅅ",
   "jei_set": "나19",
   "mean": "坐不安席",
   "idiom": "좌불안석"
 }, {
   "hanja": "ㅎㅈㅈㅂ",
   "jei_set": "나20",
   "mean": "畫中之餠",
   "idiom": "화중지병"
 }, {
   //다등급
   "hanja": "ㄱㅈㄱㄱ",
   "jei_set": "다01",
   "mean": "刻舟求劍",
   "idiom": "각주구검"
 }, {
   "hanja": "ㄱㅇㅂㄱ",
   "jei_set": "다02",
   "mean": "過猶不及",
   "idiom": "과유불급"
 }, {
   "hanja": "ㄷㄷㅅㅇ",
   "jei_set": "다03",
   "mean": "大同小異",
   "idiom": "대동소이"
 }, {
   "hanja": "ㄷㅂㅅㄹ",
   "jei_set": "다04",
   "mean": "同病相憐",
   "idiom": "동병상련"
 }, {
   "hanja": "ㄷㅎㅂㅁ",
   "jei_set": "다05",
   "mean": "燈下不明",
   "idiom": "등하불명"
 }, {
   "hanja": "ㄷㅎㄱㅊ",
   "jei_set": "다06",
   "mean": "燈火可親",
   "idiom": "등화가친"
 }, {
   "hanja": "ㅁㅇㄱㅎ",
   "jei_set": "다07",
   "mean": "明若觀火",
   "idiom": "명약관화"
 }, {
   "hanja": "ㅂㅈㄷㅅ",
   "jei_set": "다08",
   "mean": "拍掌大笑",
   "idiom": "박장대소"
 }, {
   "hanja": "ㅂㅇㅁㄷ",
   "jei_set": "다09",
   "mean": "背恩忘德",
   "idiom": "배은망덕"
 }, {
   "hanja": "ㅂㅂㅂㅈ",
   "jei_set": "다10",
   "mean": "百發百中",
   "idiom": "백발백중"
 }, {
   "hanja": "ㅅㅁㅂㅈ",
   "jei_set": "다11",
   "mean": "生面不知",
   "idiom": "생명부지"
 }, {
   "hanja": "ㅅㅌㄷㅅ",
   "jei_set": "다12",
   "mean": "小貪大失",
   "idiom": "소탐대실"
 }, {
   "hanja": "ㅅㅈㅇㅎ",
   "jei_set": "다13",
   "mean": "識字憂患",
   "idiom": "식자우환"
 }, {
   "hanja": "ㅇㅈㅈㅈ",
   "jei_set": "다14",
   "mean": "愛之重之",
   "idiom": "애지중지"
 }, {
   "hanja": "ㅇㅇㄱㅅ",
   "jei_set": "다15",
   "mean": "弱肉強食",
   "idiom": "약육강식"
 }, {
   "hanja": "ㅇㅂㅈㄹ",
   "jei_set": "다16",
   "mean": "漁父之利",
   "idiom": "어부지리"
 }, {
   "hanja": "ㅇㅇㅅㅈ",
   "jei_set": "다17",
   "mean": "類類相從",
   "idiom": "유유상종"
 }, {
   "hanja": "ㅇㅅㅇㅎ",
   "jei_set": "다18",
   "mean": "人山人海",
   "idiom": "인산인해"
 }, {
   "hanja": "ㅈㅇㅇㅅ",
   "jei_set": "다19",
   "mean": "長幼有序",
   "idiom": "장유유서"
 }, {
   "hanja": "ㅈㅎㅇㅂ",
   "jei_set": "다20",
   "mean": "轉禍爲福",
   "idiom": "전화위복"
 }, {
   "hanja": "ㅈㄱㅂㅈ",
   "jei_set": "다21",
   "mean": "衆寡不敵",
   "idiom": "중과부적"
 }, {
   "hanja": "ㅈㅌㅇㄴ",
   "jei_set": "다22",
   "mean": "進退兩難",
   "idiom": "진퇴양난"
 }, {
   "hanja": "ㅌㅅㄱㄹ",
   "jei_set": "다23",
   "mean": "卓上空論",
   "idiom": "탁상공론"
 }, {
   "hanja": "ㅍㄹㅂㄷ",
   "jei_set": "다24",
   "mean": "表裏不同",
   "idiom": "표리부동"
 }, {
   "hanja": "ㅍㅈㄷㅎ",
   "jei_set": "다25",
   "mean": "風前燈火",
   "idiom": "풍전등화"
 }, {
   "hanja": "ㅎㅎㅊㅅ",
   "jei_set": "다26",
   "mean": "咸興差使",
   "idiom": "함흥차사"
 }, {
   "hanja": "ㅎㄷㅂㅅ",
   "jei_set": "다27",
   "mean": "恒茶飯事",
   "idiom": "항다반사"
 }, {
   "hanja": "ㅎㅈㅈㄹ",
   "jei_set": "다28",
   "mean": "會者定離",
   "idiom": "회자정리"
 }, ];
